version: "3.7"
services:
  # servicio 1: La base de datos
  serv-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root.pwd
      MYSQL_DATABASE: prueba_docker
      MYSQL_USER: usr_docker
      MYSQL_PASSWORD: docker.pwd
    ports:
      # puerto externo: puerto interno
      - 3306:3306
    volumes:
      - ./database/schemas/:/var/lib/mysql
    networks:
      laravel_prod_net:
        ipv4_address: 172.21.100.9

  # servicio 2: La instalación de apache
  serv-laravel:
    build:
      # context: de donde se va a recuperar la configuración para la instalación
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8200:80
    volumes:
      - ./prueba-docker:/var/www/
      - ./prueba-docker/public:/var/www/html
    networks:
      laravel_prod_net:
        ipv4_address: 172.21.100.10
    # depends_on indica que se cree primero la bd (servicio 1)
    depends_on:
      - serv-db

# se confirman los volumenes
volumes:
  prueba-docker:
  database:
networks:
  laravel_prod_net:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 172.21.100.0/24